fail_fast: false

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/golangci/golangci-lint
  rev: v1.53.3
  hooks:
  - id: golangci-lint
    entry: golangci-lint run --fix
    require_serial: true
    verbose: true

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.9.0
  hooks:
  - id: pretty-format-yaml
    require_serial: true
    args: [--autofix, --indent, '2']
  - id: pretty-format-toml
    require_serial: true
    args: [--autofix]
