services:
  builder:
    build:
      context: ./
      dockerfile: Dockerfile
      target: builder
    environment:
      POSTGRES_HOST: postgres
    depends_on: [postgres]

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_TEMPLATE:-dev_template}
    volumes:
    - ./database/010_schema.sql:/docker-entrypoint-initdb.d/010_schema.sql
    - ./database/020_postsetup.sql:/docker-entrypoint-initdb.d/020_postsetup.sql
    tmpfs: [/var/lib/postgresql/data]
    ports: [127.0.0.1:5432:5432]
